[build]
  publish = "."

[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200

# URL bonita opcional: /gracias -> /gracias.html
[[redirects]]
  from = "/gracias"
  to = "/gracias.html"
  status = 200
